# Changes here will be overwritten by Copier
_commit: v1.0.0-beta.6
_src_path: gh:claylo/claylo-rs
categories:
- command-line-utilities
- development-tools
copyright_name: Clay Loveless
copyright_year: '2026'
edition: '2024'
has_agents_md: true
has_attestations: true
has_benchmarks: false
has_claude: true
has_claude_commands: true
has_claude_skills: true
has_cli: true
has_coda: true
has_community_files: false
has_config: true
has_core_library: true
has_editorconfig: false
has_env_files: false
has_gitattributes: true
has_github: true
has_indicatif: true
has_inquire: false
has_issue_templates: true
has_jsonl_logging: true
has_mcp_server: true
has_md: true
has_md_strict: false
has_opentelemetry: false
has_pr_templates: true
has_releases: true
has_roadmap_votes: false
has_security_md: true
has_site: false
has_skill_capturing_decisions: true
has_skill_markdown_authoring: true
has_skill_using_git: true
has_yamlfmt: false
has_yamllint: false
hook_system: none
license:
- Apache-2.0
- MIT
lint_level: strict
msrv: 1.88.0
owner: claylo
pinned_dev_toolchain: 1.93.1
preset: standard
project_description: Quality gate tooling for building-in-the-open artifacts
project_name: bito-lint
